/* TRANSACTION */
-- MYSQL 기본적으로 COMMIT이 자동으로 되므로 수동으로 조절하고 싶으면 AUTO COMMIT 설정을 바꿔 주어야한다.

-- AUTO COMMIT 활성화
SET AUTOCOMMIT = 1;
SET AUTOCOMMIT = ON;

-- AUTO COMMIT 비활성화
SET AUTOCOMMIT = 0;
SET AUTOCOMMIT = OFF;

-- START TRANSACTION 구문을 작성하고 DML 작업 수행후 COMMMIT 또는 ROLLBACK을 하면 된다.
START TRANSACTION;

SELECT * FROM TBL_MENU;

-- MENU_CODE는 AUTO INCREMENT라 NULL값을 넣어주면 자동으로 번호 증가
INSERT INTO TBL_MENU VALUES(NULL, '바나나해장국', 8500, 4, 'Y');
UPDATE TBL_MENU SET MENU_NAME = '수정된 메뉴' WHERE MENU_CODE = 5;
DELETE FROM TBL_MENU WHERE MENU_CODE = 7;

ROLLBACK;

-- 저장한 후에는 되돌아갈 수 없다.
COMMIT;


