/* CAST FUNCTION */

/* 명시적 형변환 */
-- CAST(expression AS 데이터형식 [(길이)])
-- CONVERT(expression AS 데이터형식 [(길이)])
-- 데이터 형식으로 가능한 것은 BINARY, CHAR, DATE, DATETIME, DECIMAL, JSON, SIGNED INTEGER, TIME, UNSIGNED INTEGER 등이 있다.)

SELECT 
    AVG(MENU_PRICE)
FROM
    TBL_MENU;

SELECT CAST(AVG(MENU_PRICE) AS SIGNED INTEGER) AS '평균 메뉴 가격' FROM TBL_MENU;
SELECT CONVERT(AVG(MENU_PRICE), SIGNED INTEGER) AS '평균 메뉴 가격' FROM TBL_MENU;

SELECT CAST('2025$5$20' AS DATE);
SELECT CAST('2025/5/20' AS DATE);
SELECT CAST('2025%5%20' AS DATE);
SELECT CAST('2025@5@20' AS DATE);

SELECT 
    CATEGORY_CODE, CONCAT(CAST(MENU_PRICE AS CHAR (5)), '원')
FROM
    TBL_MENU;

-- 카테고리별 메뉴 가격 합계 구하기
SELECT
	CATEGORY_CODE,
    CONCAT(CAST(SUM(MENU_PRICE) AS CHAR(10)), '원')
FROM TBL_MENU
GROUP BY CATEGORY_CODE;


-- 암시적 형변환
SELECT '1' + '2'; -- 각 문자가 정수로 변환됨
SELECT 
    CONCAT(MENU_PRICE, '원')
FROM
    TBL_MENU;
SELECT '2025-05-20'; -- 날짜 형식으로 암묵적 형변환

