-- 학생 테이블
CREATE TABLE STUDENT (
  STUDENT_ID INT PRIMARY KEY,
  STUDENT_NAME VARCHAR(50),
  MAJOR VARCHAR(50)
);

-- 수강 과목 테이블
CREATE TABLE COURSE (
  COURSE_ID INT PRIMARY KEY,
  STUDENT_ID INT,
  COURSE_NAME VARCHAR(50)
);

-- STUDENT 테이블
INSERT INTO STUDENT VALUES (1, '지민', '컴퓨터공학');
INSERT INTO STUDENT VALUES (2, '현우', '기계공학');
INSERT INTO STUDENT VALUES (3, '수빈', '전자공학');
INSERT INTO STUDENT VALUES (4, '예진', '디자인');
INSERT INTO STUDENT VALUES (5, '태영', '컴퓨터공학');

-- COURSE 테이블
INSERT INTO COURSE VALUES (101, 1, '자료구조');
INSERT INTO COURSE VALUES (102, 1, '알고리즘');
INSERT INTO COURSE VALUES (103, 2, '열역학');
INSERT INTO COURSE VALUES (104, 3, '회로이론');
-- 학생 4, 5는 수강 과목 없음